version: '3.7'

services:
  nginx:
    image: nginx
    networks:
      - traefik_web
    container_name: blog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.dbyte.xyz`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=lets-encrypt"
    volumes: 
      - ./_site:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  traefik_web:
    external: true
